// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYs8xovAkqe9MlkVMZqcYEBe8ly4ZWBIY',
    appId: '1:362152940762:web:0d366e563eac9c97c381e3',
    messagingSenderId: '362152940762',
    projectId: 'fruithub-8b7ba',
    authDomain: 'fruithub-8b7ba.firebaseapp.com',
    storageBucket: 'fruithub-8b7ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzfcserVRUyx1Y9KGyH0raE90Er-p0Fc',
    appId: '1:362152940762:android:4994511c4fc9f168c381e3',
    messagingSenderId: '362152940762',
    projectId: 'fruithub-8b7ba',
    storageBucket: 'fruithub-8b7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wQ6HMTUNdqtcR3orcXYGs4q_N5KLgEs',
    appId: '1:362152940762:ios:3d9ab371c2ba1e96c381e3',
    messagingSenderId: '362152940762',
    projectId: 'fruithub-8b7ba',
    storageBucket: 'fruithub-8b7ba.firebasestorage.app',
    iosBundleId: 'com.example.gtoceryApp2',
  );
}
